### ISSUE TITLE
Crash in tutorial notebook `accumulated_local_effect_tutorial.ipynb`

### ISSUE THREAD

**Issue by jvpeetz** [monte-flora/py-mint#66]
The tutorial notebook `accumulated_local_effect_tutorial.ipynb` crashes in `In[25]` where `plot_importance()` is called the second time.
As far as I understand, this happens because `ale_var_1d_reg['ale_variance_rankings__Random Forest']` contains feature names and not pairs of feature names (`'f1__f2'`). Such pair names are generated in the call to `find_correlated_pairs_among_top_features()` in function `_add_correlated_brackets()` but they are not stored and returned to function `plot_variable_importance()`.
But I'm clueless, how to repair this. Or should the pair names be put into dataset `ale_var_1d_reg` before calling `plot_importance()`?
Regards,
Jörg.

**Comment by monte-flora** [comment]
The issue was that I meant single variable rankings to be annotated by brackets while a color change in the text annotated paired feature rankings. However, in the code I forgot to include `ale_variance` results in the single variable methods. I've addressed this issue and now the whole `accumulated_local_effect_tutorial.ipynb` runs without crashing. Thanks for pointing out this error! Let me know if you find any other errors!

**Comment by jvpeetz** [comment]
Thanks. Yes, now the notebook looks fine. Your tutorial and your documentation are very helpful.
Regards, Jörg.
